---
  - name: Static-website-hosting
    cloudformation:
      stack_name: "Static-website-hosting-final-stack-{{user_name}}"
      state: present
      region: "ap-northeast-1"
      disable_rollback: true
      template: "cloudformation/exercise-static-website-hosting-final.yml"
      stack_policy: "policies/stack-policy.json"
      template_parameters:
        BucketName: "{{bucket_name}}"
        IndexDocument: "{{index_document}}"
        DNSName: "{{dns_name}}"
        HostedZoneName: "{{hosted_zone_name}}"
        HostedZoneId: "{{hosted_zone_id}}"
