AWSTemplateFormatVersion: "2010-09-09"
Description: Exercise-1

Parameters:
  BucketName:
    Type: String
    Description: Bucket Name

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
